-- Alterações opcionais para a versão com alertas, pesquisa global, histórico/custos e anexos.
-- Rode no Supabase apenas se as colunas/tabelas ainda não existirem.

-- Multas: descrição livre e data em que foi enviada ao RCA da empresa.
alter table if exists public.multas
  add column if not exists descricao text,
  add column if not exists envio_rca date;

-- Manutenções e produção: campo simples para guardar link/nome de anexo.
alter table if exists public.manutencoes
  add column if not exists anexo text;

alter table if exists public.producao_dia
  add column if not exists anexo text;

-- Veículos: usado nos custos/histórico, caso ainda não exista.
alter table if exists public.veiculos
  add column if not exists renavam text;

-- Tabela opcional para anexos futuros via Supabase Storage.
create table if not exists public.anexos_frota (
  id bigint generated by default as identity primary key,
  modulo text not null,
  registro_id bigint,
  placa text,
  titulo text,
  arquivo_url text not null,
  criado_em timestamptz not null default now()
);

alter table public.anexos_frota enable row level security;

drop policy if exists "anexos_frota_select_public" on public.anexos_frota;
create policy "anexos_frota_select_public"
on public.anexos_frota
for select
to anon
using (true);

drop policy if exists "anexos_frota_insert_public" on public.anexos_frota;
create policy "anexos_frota_insert_public"
on public.anexos_frota
for insert
to anon
with check (true);

drop policy if exists "anexos_frota_update_public" on public.anexos_frota;
create policy "anexos_frota_update_public"
on public.anexos_frota
for update
to anon
using (true)
with check (true);

drop policy if exists "anexos_frota_delete_public" on public.anexos_frota;
create policy "anexos_frota_delete_public"
on public.anexos_frota
for delete
to anon
using (true);
